apiVersion: v1
kind: Service
metadata:
  name: conversor-codigo-fonte-ui-service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
  selector:
    app: conversor-codigo-fonte